### ISSUE TITLE
Bad argument for  scipy.sparse.coo_matrix

### ISSUE THREAD

**Issue by MaximeBeauchene** [lmcinnes/umap#10]
I want to use umap.UMAP().fit_transform(X) but i got an error : 
ValueError: negative column index found
from the scipy function scipy.sparse.coo_matrix

When i have investigated, i've found in umap_.py, in the function fuzzy_simplicial_set(), the variable tmp_indices contains values < 0 (-1), but scipy.sparse.coo_matrix need values >= 0 !

Thx for answering me.

**Comment by lmcinnes** [comment]
Hi,

Thanks for tracking down the details. In summary the issue is the following: umap uses an approximate k-neighbor algorithm to find the ``n_neighbors`` points closest to each point. Apparently that algorithm has failed to find the full ``n_neighbors`` points (with the remaining neighbors set to a flag value of -1). As you note, this breaks a lot of stuff downstream in the code. First of all some better error checking so that a more sensible error message is displayed would be useful, so I'll try to get that done ASAP. After that it is a matter of tracking down why the approx knn algorithm is failing, which may take longer to sort out.

**Comment by lmcinnes** [comment]
I believe I have resolved the error, but would appreciate it if you could check if that is the case using the current master. Let me know if it works now, thanks!

**Comment by MaximeBeauchene** [comment]
I have cloned your git :    
git clone https://github.com/lmcinnes/umap.git

After i have done : python3 setup.py install
And i still have the same issue !

**Comment by MaximeBeauchene** [comment]
The git log say the last commit is : 

commit da6fe794e7255811798708661319aaa1d81da604
Author: Leland McInnes <leland.mcinnes@gmail.com>
Date:   Mon Nov 13 11:46:01 2017 -0500

    Match new calling convention better

5 hours before you answered me, have you push the fix ?

**Comment by lmcinnes** [comment]
I did indeed push the fix. I have found that I sometimes need to purge the previous version from my site-packages directory prior to a re-install before it takes. Could that be an issue?

**Comment by MaximeBeauchene** [comment]
Thanks a lot !

It is working great. 

Good job.
