### ISSUE TITLE
Umap issue

### ISSUE THREAD

**Issue by garretvo19** [lmcinnes/umap#101]
Hi, 

 I installed your package and tried to follow your example. I got the following error: There is no module UMAP in umap. Can you please let me know  ?

**Comment by lmcinnes** [comment]
I believe the issue here is that there was already a package called 'umap'
on PyPI, and accordingly I had to name this package something else. To
install this package you'll likely need to do
```bash
pip uninstall umap
pip install umap-learn
```
Beyond that you can try some of the options available in the FAQ:
http://umap-learn.readthedocs.io/en/latest/faq.html#i-can-t-get-umap-to-run-properly

Note that this includes the umap package from PyPI causing issues.

**Comment by sleighsoft** [comment]
Please create a new issue if problems still exist.
