### ISSUE TITLE
umap 0.5.4 is causing a broken package error in Conda feedstock builds

### ISSUE THREAD

**Issue by RogerHYang** [lmcinnes/umap#1054]
With UMAP 0.5.4 we're seeing a broken package [error](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=784469&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=761) in our Conda feedstock builds

## 0.5.4: broken package
<img width="511" alt="Screenshot 2023-09-20 at 10 03 33 AM" src="https://github.com/lmcinnes/umap/assets/80478925/ac90d796-6da6-4fab-9e50-8320b94d6c13">

## 0.5.3: no problem
<img width="446" alt="Screenshot 2023-09-20 at 10 56 25 AM" src="https://github.com/lmcinnes/umap/assets/80478925/7eda9f72-4343-4269-beb9-1132f1e75fae">

**Comment by lmcinnes** [comment]
We actually weakened/removed requirements on tbb. It also seems odd since it looks like it is installing tbb via conda, so I really don't quite know what is going astray with pip check. I admit this is into weeds of python packaging that I am less familiar with. Any suggestions of what to actually look at would be appreciated.

**Comment by hamelin** [comment]
We have dropped reliance on package TBB on non-Intel platform, so as to support installing on ARM-based Apple computers. Could you please give more information on the platform where you observe this error?

**Comment by RogerHYang** [comment]
> We have dropped reliance on package TBB on non-Intel platform, so as to support installing on ARM-based Apple computers. Could you please give more information on the platform where you observe this error?

The error is from our Conda feedstock build, and the log can be seen [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=784469&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=761). it seems to be running on a linux 64 system

**Comment by hamelin** [comment]
Good news: I can duplicate the problem in a local environment. The bad news: this seems to be because the list of packages that Pip sees is a subset of what gets installed. To wit, `conda list` gives something close to what @RogerHYang reported:

![image](https://github.com/lmcinnes/umap/assets/240427/8ffcd4de-cd4a-47ce-94f1-c7c512844f48)

Then `pip list` is less profligate:

![image](https://github.com/lmcinnes/umap/assets/240427/17f492f6-637b-4eed-9441-fa9745f355cb)

This is likely why `pip check` fails: if it cannot see `tbb` in its package listing, it cannot possibly figure out the proper dependency structure of `umap-learn`.

I will investigate this behavior further. However, @RogerHYang, I ask out of curiosity: what is the purpose of checking dependency resolution with `pip check` when all the dependencies are expected to be resolved from the Conda-Forge package set?

**Comment by hamelin** [comment]
Also, to be clear: this doesn't seem to be a direct UMAP problem, but rather a brittle behavior from the mixture of Conda and Pip.

**Comment by RogerHYang** [comment]
Thank you for the analysis @hamelin. This is new to me and I used [grayskull](https://github.com/conda/grayskull) to generate the `meta.yaml` that has the `pip check`, which is in fact unnecessary as you pointed out. I'll mark this issue as resolved.
