### ISSUE TITLE
`tbb` optional requirement should be configurable

### ISSUE THREAD

**Issue by mithaler** [lmcinnes/umap#1060]
In [PR 1045](https://github.com/lmcinnes/umap/pull/1045), this project added configuration to its `setup.py` to install `tbb` only if the current machine is x86, to allow ARM machines to install it. Unfortunately there are some workflows this isn't sufficient for; in some cases some of an organization's machines might be x86 and others might be ARM, but both need to share the same compiled dependency list (perhaps created via Poetry or `pip-compile`), causing a dependency list produced on one architecture to create broken builds on others.

Would it be reasonable to move `tbb` to `extras_require`, perhaps under an extra named something like `x86`? That would allow more flexibility in installation, especially if the project can run on x86 even without it. (I'm willing to submit a PR to do this myself, but only if the project would accept it.)

**Comment by lmcinnes** [comment]
Ping @hamelin

**Comment by hamelin** [comment]
The point of including package `tbb` is that Numba can leverage it on Intel CPUs as a fast parallel computing option (at least, faster than some of the fallbacks). As such, putting it up as an explicit installation option sounds like a good approach. @mithaler, if you would please propose a PR with the change, I would review and accept it. I have two requests, however:

1. Could you please name the option `tbb` rather than `x86`? The choice is about providing a fast option for Numba to use, not about selecting a CPU; installing on x86[-64] will work regardless of whether the option is used or not.
2. Could you draft a rationale and example of using this option under [the **Installing** section](https://github.com/lmcinnes/umap#installing) of the README file as part of the PR? I won't bikeshed the wording, and work out the final text on my own, but an initial write-up will save me that much effort.

Thank you very much!

**Comment by skupr-anaconda** [comment]
I found that the usage of `tbb` isn't described in the `README.md `. 
As the source code doesn't rely on `tbb` directly I would say that it's really an _optional_ dependency and **not** required

**Comment by mithaler** [comment]
PR is up (#1066), thanks for the quick response!
