### ISSUE TITLE
UMAP vs. PCA vs. VAE

### ISSUE THREAD

**Issue by snakers4** [lmcinnes/umap#113]
Some time ago I made this [repository](https://github.com/snakers4/playing_with_vae) which essentially took an easy domain (FMNIST) and applied / compared several embedding techniques: PCA / UMAP / VAE.

I was wondering id anything like that will be useful as an example.
If so - should I stick everything in one .ipynb notebook and just add a PR with this notebook?

Or maybe just this image will serve as a decent illustration?
![](https://raw.githubusercontent.com/snakers4/playing_with_vae/master/compare.png)

**Comment by lmcinnes** [comment]
Thanks for working through all of that, it looks like some very interesting experiments. Some suggestions for the UMAP embedding: I would strongly suggest using ``n_neighbors`` >= 10 if you are interested in knn accuracy using 10 neighbors. I would also strongly suggest you use ``init='spectral'`` if at all possible.

As for how best to include this with the project -- your notebook is quite large and complex and deals a lot with VAEs, so directly including the notebook here doesn't seem the best approach. The illustration is quite useful, and I may add it into the documentation somewhere. What might well be beneficial, however, would be to add a question to the FAQ on how UMAP compares to VAEs (since I suspect it is a question many might have) with the answer giving an outline of your results and then linking directly to your repository for further details. I would be happy to accept a PR for such a change if you are interested.

**Comment by snakers4** [comment]
> Some suggestions for the UMAP embedding: I would strongly suggest using n_neighbors >= 10 if you are interested in knn accuracy using 10 neighbors. I would also strongly suggest you use init='spectral' if at all possible.

Yeah, when uploading an example I will rerun this bit to see if it differs.
In case of knn neighbors it is kind of obvious why I should try using more (even though 5-10 neighbors were optimal anyway), but what is the key difference between `random` and `spectral`? 
Could not find it in the docs.


>  What might well be beneficial, however, would be to add a question to the FAQ on how UMAP compares to VAEs (since I suspect it is a question many might have) with the answer giving an outline of your results and then linking directly to your repository for further details. I would be happy to accept a PR for such a change if you are interested.

Ok, why not, I will do it in near future

**Comment by jc-healy** [comment]
The difference between `random` and `spectral` is that `random` throws down the points randomly in your low dimensional space, then moves them around to optimize the objective function.  It tends to give more variance in the embeddings and makes your optimizer work harder.
`spectral` on the other hand initializes the layout with a spectral embedding of the nearest neighbour graph that UMAP has constructed.   If you're unfamiliar with spectral embeddings just thing of it as the eigenvectors of the laplacian of the graph.  This starts you off with a better solution which tends to result in better answers.  Unfortunately you can occasionally run into issues with the stability of the eigensolver which might mean you need to fall back on `random` (or add small amounts of jitter to your data).

**Comment by snakers4** [comment]
Added a PR 
First time I do anything like this
https://github.com/lmcinnes/umap/pull/119


> Yeah, when uploading an example I will rerun this bit to see if it differs.

It kind of did not matter
Played a bit with this, no real difference
