### ISSUE TITLE
What would be the best distance metric for missing data?

### ISSUE THREAD

**Issue by ensonario** [lmcinnes/umap#115]
I have a dense dataset with about 5-10% of missing data in various columns. It feels lite it still should be possible to calculate distance between points, just by removing missing values for each pair. Is there more scientific approach to this? May be even this kind of metric was implemented and available somewhere.

An interesting discussing here: https://stackoverflow.com/questions/24781461/compute-the-pairwise-distance-in-scipy-with-missing-values

**Comment by lmcinnes** [comment]
I'm not sure ignoring the values is really the right thing to do here. For example a vector with all data missing would become distance 0 from every other point -- that certainly isn't the right approach here. There was a nice talk at SciPy this year on handling missing data: https://www.youtube.com/watch?v=2gkw2T5jAfo . Unfortunately the summary is that there are no easy answers. It is important for a start to know *why* your data might missing before you can start to figure out how to deal with that.

**Comment by ensonario** [comment]
Thanks for the link.

You're right if all values for the row are missing, but what if there is something like:

`numpy.random.seed(123456789)`
`data = numpy.random.rand(3, 10) * 5`
`data[data < 1.0] = numpy.nan`

I.e. just a small fraction if different columns is missing. It feels like you still should be able to reconstruct the distance...

**Comment by lmcinnes** [comment]
It depends on why the values were missing. If they were measurements via
some sensor and they are missing because they exceeded the sensors
threshold/scale (too large, too small, etc.) then the distances should be
much larger for those vectors. Under a different missingness regime perhaps
the distances should be much smaller when the data is missing. You really
don't know unless you know more about the missingness regime. You can drop
the rows with missing data, but that will be biasing your results in a
different way. For dimension reduction that might be the least bad thing
you can do, but you should make careful note that you are doing it, and the
impacts that might have on the results (perhaps vectors with missing data
are crucial to reconstructing the manifold).

**Comment by ensonario** [comment]
Thanks Leland, the topic is definitely complex.

**Comment by ivokwee** [comment]
What about using correlation on pairwise complete pairs? R has this option as in  cor(X, use="pairwise.complete"). Of course completely missing values will still give NA.

**Comment by jlmelville** [comment]
@mpauper sparse matrices (at least as input to UMAP) can't contain missing data either. The only difference between a sparse and dense matrix from the perspective of UMAP is that the zeros in a sparse matrix are not explicitly stored.

**Comment by mpauper** [comment]
> @mpauper sparse matrices (at least as input to UMAP) can't contain missing data either. The only difference between a sparse and dense matrix from the perspective of UMAP is that the zeros in a sparse matrix are not explicitly stored.

Thank you, that is very clear! There's various places on the internet (stack overflow) etc. where people mention that UMAP can deal with missing data, which lead to my confusion.
