### ISSUE TITLE
How does UMAP estimates/evaluates variance? 

### ISSUE THREAD

**Issue by cartal** [lmcinnes/umap#122]
Hi, 

Thanks for develop UMAP. Is such a superb tool. 

My question is regarding how much variance can be explained by UMAP. I have been through he documentation, and is possible that this is explained somewhere in the preprint, but I may have missed it. 

Can you provide with an explanation or a place where I can find this? 

Thanks!

**Comment by lmcinnes** [comment]
As a non-linear manifold learning technique that ultimately works with
metric spaces at its heart rather than feature based data UMAP doesn't
really have a notion of explained variance the way algorithms like PCA do.
A colleague is working on developing some alternative measures of how well
an embedding has performed, but that is still preliminary work and we don't
have any published code for that yet -- ultimately UMAP remains a research
project with additional features and utilities still being developed.

**Comment by cartal** [comment]
Thank you so much!

**Comment by shadiakiki1986** [comment]
> A colleague is working on developing some alternative measures of how well
> an embedding has performed, but that is still preliminary work and we don't
> have any published code for that yet

Is there an update for this?

**Comment by lmcinnes** [comment]
No updates I'm afraid. Ideas didn't pan out as well as hoped and we had to move on to other things. Sorry.

**Comment by edebonneuil** [comment]
One might get a fake "% variance explained" by using the inverse UMAP to get a reconstruction error, adjusting that error based on reference cases as an attempt to remove the error linked to the stochastic reconstruction process, and expressing the %variance explained as if the reconstruction error was in the context of a PCA : https://github.com/lmcinnes/umap/issues/44 But it is highly experimental

**Comment by jrudar** [comment]
This is a little late, but one thing I did was performing a PCA after performing UMAP. This at least will give you the variation along each PC in the UMAP projection.

**Comment by Patricklv** [comment]
Just curious to learn given UMAP is not directly amenable to the variance-per-PC like question, how about the gradients from diffusion map embedding? Variance in data explained by each gradient, is it a legitimate question?
