### ISSUE TITLE
Add plotting functions

### ISSUE THREAD

**Issue by lmcinnes** [lmcinnes/umap#127]
As per @terrytangyuan in openjournals/joss-reviews#861 , it would be helpful to have an extra "plotting" module that can provide simple utility plotting functions to make visualization easier for new users. In particular it should probably make use of seaborn's new ``relplot``, and provide an easy interface to datashader for large-scale data.

**Comment by iggisv9t** [comment]
Why `replot` when there is matplotlib's `scatter`? Why datashader, when there is `hist2d` in matplotlib?

For example I draw outputs from UMAP here with this functions for big dataset: https://github.com/iggisv9t/graph-stuff/blob/master/Graph%20Embeddings%20Tutorial.ipynb
`hist2d` can handle up to billions points.

Datashader is too unstable in my experience. Seaborn does not allow to make all necessary tweaks such as opacity or point size. You need to fallback to matplotlib api in order to do that.

**Comment by raghavmecheri** [comment]
> As per @terrytangyuan in [openjournals/joss-reviews#861](https://github.com/openjournals/joss-reviews/issues/861) , it would be helpful to have an extra "plotting" module that can provide simple utility plotting functions to make visualization easier for new users. In particular it should probably make use of seaborn's new `relplot`, and provide an easy interface to datashader for large-scale data.

I ended up building a wrapper to plot UMAP embeddings for a project (uses relplot) which I could try and add in post some cleanup if you're still looking to integrate this.

**Comment by lmcinnes** [comment]
@raghavmecheri I actually ended up implementing a lot of this myself, but then never closed this issue. Sorry.
