### ISSUE TITLE
"Loadings" for UMAP

### ISSUE THREAD

**Issue by budach** [lmcinnes/umap#129]
Hi,

I don't fully understand UMAP, yet, and might have missed it. For PCA it is possible to get the loadings for a component to see how much each original feature contributes to that component (this is easy as it is only a linear transformation). Can I get something similar for the UMAP components?

**Comment by lmcinnes** [comment]
Since UMAP isn't a linear transform, and ultimately works on distances
rather than features, no there is no immediate equivalent. If strong
interpretability in terms of source features is critical then UMAP is not
necessarily your best option. I would note that there is an incoming pull
request that will hopefully be available in version 0.4 that implements an
inverse transform, allowing you to take a point in the low dimensional
space and find a corresponding high dimensional equivalent. While this is
no replacement for explicit feature coefficients, it does start to allow
some exploratory analysis of feature interactions with the embedding. I
expect that will be the best that will be available for the immediate
future. Sorry I can't be more help.

**Comment by budach** [comment]
No worries. Thanks for the info.

**Comment by carlospence** [comment]
Is there any update on generating loadings or contributions for UMAP?
