### ISSUE TITLE
poincare disk model of hyperbolic geometry

### ISSUE THREAD

**Issue by kousun12** [lmcinnes/umap#205]
Any chance we can get in a poincare metric? I'm working on embeddings in hyperbolic space in the poincare ball model, and would love to get some visualizations of points in the n-d unit balls down to the poincare disk. 

Is my premise even reasonable, given how umap works?

**Comment by kousun12** [comment]
https://github.com/kousun12/tf_hyperbolic is the project. the janky plot i have up on the readme is plotting a trained set of weights in 2-space

**Comment by lmcinnes** [comment]
That is certainly possible. Depending on how keen you are to have it you can build the 0.4dev branch and write your own version of poincare disk distance, along with an associated gradient (see the ``euclidean_grad`` functions in ``distance.py`` for example) and pass it as the ``output_metric``. Otherwise this is on the list of things I would like to do, but I haven't gotten around to writing poincare distance (or, more importantly the associated gradient). If you want to write such a thing and submit a pull request I would be very happy to accept it. Otherwise ... it is on the roadmap, but I don't have immediate plans for it.

**Comment by kousun12** [comment]
got it. i've already a version of those in my project, so I'll spend some time submitting a PR to ya today

**Comment by lmcinnes** [comment]
Sounds great! I'm a little strapped for time right now, so please forgive any slowness in getting the PR reviewed. Thanks for  taking the trouble -- this would definitely be a nice feature and I imagine you are far from the only person who will be interested in using it.

**Comment by sleighsoft** [comment]
Hey @kousun12 it looks like your PR for this issue went through. Can this issue be closed? If so, please close it :)

**Comment by lmcinnes** [comment]
In practice a hyperboloid model of hyperbolic space is what got implemented, and the user can convert that to the Poincare disk model after the fact. There are issues with parameterisation of the embedding manifold that make the disk model hard. You can [see more details in the 0.4dev docs](https://umap-learn.readthedocs.io/en/0.4dev/embedding_space.html#bonus-embedding-in-hyperbolic-space).
