### ISSUE TITLE
Precomputed distances

### ISSUE THREAD

**Issue by LGro** [lmcinnes/umap#26]
Would you be interested in / see any obstacles for implementing UMAP on a distance matrix? After a first glance this seems to be quite straight forward to include. 
I'd be inclined to contribute.

**Comment by lmcinnes** [comment]
No that's certainly quite feasible, the only catch being that you have to have computed the distance matrix first. I would be happy to work though and merge a pull request if you want to put in the work. Thanks!

**Comment by LGro** [comment]
Sure, should be helpful in the cases where people have precomputed distance matrices. 
I have a working implementation already (looks very nice!) and will submit a pull request in the upcoming days.

So far I have added a `precomputed` flag to `make_nn_descent` that is set when the given metric is set to the string precomputed. However, I'm still struggling with what to do with the distance function in that case, because it seems like it expects a numba function in any case. 
Would you prefer a flag that changes the behaviour or a dummy distance function named `precomputed` that is then checked for its name in `nn_descent`? 
Maybe we can come up with an even more elegant way.

If I couldn't make clear what I mean just wait for my pull request and we can discuss the actual code.

**Comment by lmcinnes** [comment]
I think adding a dummy distance function called ``precomputed`` to distance.py is probably the better way to go under those options (would likely have less code duplication).

Since you have the full distance matrix, however, could you not compute the nearest neighbors by an argsort across an index of the distance matrix? That might save you having to mess with nn_descent at all. Then again, if you have something that works I'm not really going to argue.

**Comment by LGro** [comment]
You are right, that's more elegant and faster.
