### ISSUE TITLE
0.4 release timeframe

### ISSUE THREAD

**Issue by ivirshup** [lmcinnes/umap#281]
Over at scanpy we've noticed we have some incompatibilities with the `0.4dev` branch (https://github.com/theislab/scanpy/issues/779). I'm trying to figure out if we should start changing our code now or if we should wait. Is there any chance you have a timeframe for the next release? Also, are you planning on having a release candidate before making a stable release? Thanks!

(cc: @gokceneraslan)

**Comment by lmcinnes** [comment]
I was hoping to get a release out in the next few months. I hadn't considered doing a release candidate process, but since there are some non-trivial dependent projects that actually sounds like a good idea. I will try to make a release candidate soon and see how things go from there. Thanks for this!

**Comment by ivirshup** [comment]
A release candidate would be very useful for us, thanks!
