### ISSUE TITLE
Should be resolved in 0.3.10

### ISSUE THREAD

**Issue by penglbio** [lmcinnes/umap#300]
Should be resolved in 0.3.10
I also have same problem with you. So is the warning caused by the umap-learn package? 
_Originally posted by @sleighsoft in https://github.com/lmcinnes/umap/issues/252#issuecomment-528449868_

**Comment by sleighsoft** [comment]
Yes, this warning is caused by umap-learn package and is just that. A warning that numba, a package used to speed up code execution by JIT compiling code, could not optimize the code that was annotated to be JIT compiled.

This is 100% my bad. I thought @lmcinnes added this to 0.3.10 but I think it only made it into the upcoming release of 0.4.

The PR for the changes is here https://github.com/lmcinnes/umap/pull/287

Thanks for pointing this out again @penglbio.

I will close this issue and add this comment to the issue you referenced as well!
