### ISSUE TITLE
cheating UMAP when you know many pairs of proximal neighbors

### ISSUE THREAD

**Issue by bzip2** [lmcinnes/umap#326]
Hi.

UMAP is extraordinary and I'm trying to avoid resorting to PCA, partly out of curiosity, partly so I can claim, "this is pure UMAP - no PCA here". Let's say that I know of many pairs of proximal vectors, either because I've done UMAP already, or from calculating Euclidean distances on the original data. Now, I want to do UMAP on the combination of multiple data sets, and they're sufficiently different that applying the embedding of one to the other(s) might give me weird results (e.g. some degree of forced conformity). I haven't tried, but let's say it's true. At least one data set takes a long time to give me an embedding, so I'm looking for a shortcut.

An obvious shortcut to try is to avoid reclustering many pairs of vectors that I already know belong fairly close to each other in the embedding, but 1) excluding a member of each such pair, 2) doing the embedding, and 3) reapplying the embedding on excluded vectors would skew the results by altering the determination of neighboring vectors.

Could I feed UMAP an initial mapping that is random except that I've set the positions of proximal pairs of vectors to be identical, or nearly identical? This seems easy to try, but I worry about violating some underlying assumption, and maybe it won't save any time.

Here's another possible approach, though it would involve modifying the code, or might be completely redundant. Could I assign an optional weight to each vector (let's call it "ego"), an integer that represents the number of neighbors it really represents (1 by default), so that if I exclude some vectors, do the mapping with egos >=1, save the embedding, then map the excluded samples with egos = 1, I should get results similar to doing UMAP on everything, but faster?

**Comment by lmcinnes** [comment]
There is a lot to unpack there -- so please bear with me as I try to take this a piece at a time.

First of all -- is one of the things you want to be able to do: seed the nearest neighbor computation with some information about neighbors to hopefully speed it up? That is certainly possible if you are willing to get your hands dirty and mess around with the internals (call internal functions yourself and piece together the bits to do the end to end embedding).

Alternatively are you attempting to find a better initialization for the layout step? That is have the starting points in 2D bet "close-ish" to the expected final end result? That certainly is possible right now: the ``init`` keyword argument can accept a numpy array of positions to use as the initialization.

Your final comment seems to be speaking to condensing some of the data to some landmarks, embedding the landmarks and using that information to build a good initialization for embedding everything else. Something along these lines can work, and I have actually played with doing such things as an alternative initialization approach to ``"spectral"`` that uses graph clustering. It still needs work because there is finessing to be done to make it all work well, but it is possible if you want to play. This would require digging in an calling internal routines yourself with modifications along the way, however, and is not trivial currently.

**Comment by bzip2** [comment]
Hi. 

Thanks for the comments. I was referring to the first scenario, using information about known close neighbors to speed up the embedding. I'll start digging into the code and let you know if I get interesting results. For the init option, I didn't mean a good guess at the final embedding. I mistakenly thought that putting close vectors together in an otherwise random layout would speed things up because those pairs would stay together as they were rearranged.

The landmark approach you describe is actually better generally. I'll defer to your expertise.

**Comment by lmcinnes** [comment]
The thing you want to look into it in the nndescent routine. It initialises using the results of an rp-forest, but if you have better near neighbor information you could slip that in instead. That could potentially significantly speed up the nearest neighbor computation.
