### ISSUE TITLE
ImportError: umap.plot requires matplotlib, datashader, colorcet and holoviews to be installed

### ISSUE THREAD

**Issue by kinredon** [lmcinnes/umap#405]
Install umap using below commands:
```
pip install umap-learn
pip install "umap-learn[plot]"
```
and they run successfully.

but when I `import umap.plot`, it occurs:

![image](https://user-images.githubusercontent.com/39270545/79442387-109de400-800b-11ea-8d95-98e6cdcf5d73.png)

But actually, these packages `matplotlib, datashader, colorcet and holoviews` have been installed.

so what I should do to fix this error? 

Big thanks!

**Comment by rn123** [comment]
I had the same issue and had to install the `imgcat` package as well.

**Comment by pramitchoudhary** [comment]
Recently, ran into this above didn't help.

**Comment by gimlidc** [comment]
Error of mine goes from 'nansum_missing' from 'datashader.utils' ... digging into...

**Comment by ichitaka** [comment]
Sadly same problem here

**Comment by Abhilash-Korraprolu** [comment]
Hi!

It gave me the same error. So I manually imported each of these (matplotlib, datashader, colorcet and holoviews), to see if they were all fine. Turns out there was an error while importing holoviews. 

So i did pip install holoviews. And turns out it got updated to the recent version. I think umap didn't install the required latest package. Hope this helps. :)

Also, small note for just in case: I did fit_transform and was wondering why it was throwing error. I remembered I had to only fit() as use that object. 

Here's what it looked like:
<img width="956" alt="Screenshot 2020-08-03 at 10 32 28 PM" src="https://user-images.githubusercontent.com/42868745/89208797-ac635800-d5da-11ea-9ad6-37735684d8aa.png">

**Comment by Abhilash-Korraprolu** [comment]
Hi!

**A suggestion, not solution.**
I got this error in my jupyter notebook as well. The problem was with importing holoviews. But since, thats not your issue:
This is the code that from which the error is being raised. You could try executing this code and see if you could find any error. It may not solve your problem, but give it a shot.

`    import pandas as pd
    import datashader as ds
    import datashader.transfer_functions as tf
    import datashader.bundling as bd
    import matplotlib.pyplot as plt
    import colorcet
    import matplotlib.colors
    import matplotlib.cm

    import bokeh.plotting as bpl
    import bokeh.transform as btr
    import holoviews as hv
    import holoviews.operation.datashader as hd`

**Comment by mwalmsley** [comment]
This was a great suggestion for me - I found my datashader needed numba != 0.50.1 to use CUDA, which umap.plot wants, so a quick numba update solved the error.

**Comment by apblair** [comment]
@pramitchoudhary Also, a great suggestion for me! Thanks

**Comment by GAnagno** [comment]
pip install umap-learn[plot] solves the issue

**Comment by tinakeshav** [comment]
I still have this problem with numba version 0.51.2 & umap-learn  0.5.0

**Comment by sudoku-lord** [comment]
I had to remove the try/except block to figure out what was going on with mine, since all the dependencies listed in the exception were up to date for me. Turns out I had to deprecate `dask` to the previous version for it to work.
