### ISSUE TITLE
Question: why not use the distances in optimize_layout?

### ISSUE THREAD

**Issue by Fil** [lmcinnes/umap#509]
For context, my use case is to have the UMAP graph as one of the forces of a (D3.js) force simulation. The goal would be 1) to have a smoother resolution of the graph, in particular thanks to the [Barnes-Hut implementation](https://github.com/d3/d3-force#many-body) of the repulsive ("many body") force  and 2) to be able to mix with other forces in order to add "anchor points", a collision force with variable radius, etc. (This is related to #493)

As an aside, note that I'm playing with [DruidJS's implementation of UMAP](https://github.com/saehm/DruidJS/blob/master/dimred/UMAP.js), which seems to be a rather direct port of the python original implementation.

When I return the graph and plot the edges, I get the following:

<img width="527" alt="Capture d’écran 2020-10-29 à 09 45 32" src="https://user-images.githubusercontent.com/7001/97545586-8972f500-19cb-11eb-9419-dca03131b705.png">

I have drawn the lines stronger where the link's "weight" is close to 1, but some weights appear to be 1e-10 or even smaller.

What surprised me (if I have read the code correctly) is that all the edges, independently of their weights, are considered to be of the same importance (i.e. link "strength" and "distance") for the force optimization. It seems that we're discarding useful information.

After this long introduction, I guess my question is, _why are the original distances not taken into consideration in optimize_layout?_

**Comment by Fil** [comment]
And here's the same graph as above, but this time resolved with d3-force rather than umap's optimize_layout:
<img width="777" alt="Capture d’écran 2020-10-29 à 15 06 05" src="https://user-images.githubusercontent.com/7001/97584487-614dbb00-19f8-11eb-807d-731c3efbcfb1.png">

**Comment by lmcinnes** [comment]
The short answer is that this was a performance optimization. It is entirely possible to use edge weights in the computation directly, but (for reasons that are subtle) it is slower (especially on larger datasets) than the current option which weights edges equally, but *samples* the edges proportionally to their weight. Since performance, especially on large datasets, was a major factor for this implementation I took the latter route. It is not hard to simply sample all edges each epoch and apply the edge weights to the forces -- and indeed I have had branches that do this in the past (although I think none got pushed here).  The qualitative differences were small, and the performance difference was sufficiently non-trivial that I never pursued it further. There is no reason, however, that it wouldn't necessarily be a good idea for small scale implementations.

**Comment by Fil** [comment]
As @rpgove remarks in https://bl.ocks.org/rpgove/e66f1d921718813ecf507178c7dc8d12 (and https://github.com/twosixlabs/d3-force-sampled) it is possible to use the sampled approach to get faster to a "godd enough" distribution, then end up by refining the layout with a few iterations of the Barnes-Hut approximation.
