### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by moemode** [lmcinnes/umap#525]
Hey,
is the explicit seting of random_state meant to give reproducibility across machines?
Because when running https://umap-learn.readthedocs.io/en/latest/reproducibility.html
and executing
```
%%time
mapper3 = umap.UMAP(random_state=42).fit(data)
```
I get a completely different result. But in this case the 10 classes are still nicely separated in both results.

When following https://umap-learn.readthedocs.io/en/latest/clustering.html
I got a completely different embedding too. But this time the classes were not nicely separated.
Consequently the ARI scores i got were much worse which was not a great first experience with the lib.
Even when trying out different seed values it didn't get much better.

I guess reproducibility across machines depends on the library versions used and on other factors too?

**Comment by dylanking42** [comment]
instead of worrying about reproducibility across machines why not just save the actual `UMAP()` object?

https://github.com/lmcinnes/umap/issues/152
and
https://github.com/lmcinnes/umap/issues/178

#178 has an example.

_I guess reproducibility across machines depends on the library versions used and on other factors too?_
I'm guessing yes: i think it would be hard to guarantee same exact results across unix/windows just with seed.

**Comment by lmcinnes** [comment]
Randomness is built on top of numpy's routines, and yes, that is not 100% consistent across machines, specifically across OS types. I appreciate that this is an issue, but it isn't really one that I can address unfortunately.
