### ISSUE TITLE
The umap.plot.connectivity(mapper, edge_bundling='hammer') issue: "hammer_bundle operation requires scikit-image. "

### ISSUE THREAD

**Issue by louiseyzi** [lmcinnes/umap#537]
Hi, 

When I was plotting the connectivity graph, even though I've installed the "scikit-image" and called "from holoviews.operation.datashader import datashade, bundle_graph ", it still had issues: 

raise ImportError("hammer_bundle operation requires scikit-image. "
ImportError: hammer_bundle operation requires scikit-image. Ensure you install the dependency before applying bundling.

How could I resolve this problem?

**Comment by dylanking42** [comment]
Could you try installing scikit-image? 

https://scikit-image.org/docs/dev/install.html

See if that resolves the issue.

**Comment by lmcinnes** [comment]
The master branch has this updated in the setup.py so that scikit-image should be installed if you install with the .plot option in pip. I've also tried to update some of the error messages / warnings. Ideally datashader, which is the one introducing the requirements, should be pulling down scikit-image, but regardless it should work if you just install scikit-image yourself.
