### ISSUE TITLE
ZeroDivisionError when dataset is 4096 elements or more

### ISSUE THREAD

**Issue by DavenH** [lmcinnes/umap#54]
Hi, I've narrowed in on a ZeroDivisionError that happens 100% of the time when my dataset is above >= 4096 elements, or 2^12, and none of the time when below 4096. 
Varying min_dist, bandwidth, or n_neighbours parameters doesn't avoid it. 
I tried with 3 datasets; the two that were 300 dims failed this way, but one with 600 dims had no error. 

The trace:
  ```
File "C:/W/py_tests/dim_red/umap_reduct.py", line 9, in <module>
    embedding = umap.UMAP(n_neighbors=6, min_dist=0.002, bandwidth=0.6, metric='cosine').fit_transform(df)
  File "C:\W\py_tests\venv\lib\site-packages\umap\umap_.py", line 1476, in fit_transform
    self.fit(X)
  File "C:\W\py_tests\venv\lib\site-packages\umap\umap_.py", line 1434, in fit
    self.verbose
  File "C:\W\py_tests\venv\lib\site-packages\umap\umap_.py", line 761, in fuzzy_simplicial_set
    verbose=verbose)
ZeroDivisionError: division by zero
```
This is version 0.2.1 on Windows 10. 

Thanks

**Comment by lmcinnes** [comment]
I believe what is happening here is that you have a data point that is identically zero. Since you are using cosine distance it is trying to normalise by the square root of the product of the norms and dying a horrible death. It seems I didn't have sufficient defensive programming on my cosine distance implementation -- fortunately that can be fixed. Thanks for the detailed report -- it made chasing this down much easier.

**Comment by lmcinnes** [comment]
If you have time and can pull from master and rebuild I would appreciate if you can verify if that last commit resolves the issue for you.

**Comment by DavenH** [comment]
I'll do so. It's the least I can do for this amazing tool! Will report back.

**Comment by DavenH** [comment]
Okay cool, the 0.3dev umap doesn't throw the exception. Fabulous! I'll just keep using that :)
