### ISSUE TITLE
Projecting multiple copies of the same vector

### ISSUE THREAD

**Issue by arturandre** [lmcinnes/umap#564]
Hi, I just tried to follow the tutorial and noticed that if I use fit_transform on a set with the same vector copied 100 times it gives me back a 2D projection with 100 distinct points, that's the expected behavior or it is a bug?

I expected that if I had multiple copies of the same vector in a high dimensional space it would get projected into the same point in a lower-dimensional space.

Thanks in advance for the attention! The library is amazing!

**Comment by lmcinnes** [comment]
The actual embedding process is a stochastic optimization, so the 100 points all land in a slightly different spot. Worse still, the neighborhood estimation for those points gets messed up since the 15 nearest neighbors of each of those points is ... a random sampling of the 100 duplicated points. That means you can get unlucky and have the 100 duplicated points split into distinct islands in the embedding space.

So, in some sense, the answer is that large numbers of duplicates are bad for the algorithm. If, however, you know you have lots of duplicates and you do want them to all land in the same spot in the embedding, then the answer is to use the ``unique=True`` option, which gets around this as you might expect: it embeds the unique elements of the dataset, and then drops the duplicates down on to of their unique representative. This seems like what you are after here. So you just want to do something like

```python
embedding = umap.UMAP(unique=True).fit_transform(data_with_duplicates)
```

and it will take care of all of that for you.

**Comment by arturandre** [comment]
Perfect! Thank you a lot!
