### ISSUE TITLE
Does the optimize_layout_euclidean function in layouts.py work correctly?

### ISSUE THREAD

**Issue by damdaepark** [lmcinnes/umap#587]
I wonder if the **optimize_layout_euclidean** function in layouts.py works correctly because no return is specified for the **_optimize_layout_euclidean_single_epoch** function inside it.

**Comment by lmcinnes** [comment]
The function works in place on the arrays passed in, so doesn't require a return value.

**Comment by damdaepark** [comment]
Could you help me to figure out what I'm missing?

I checked if the **head_embedding** variable inside **optimize_layout_euclidean** function has been changed after running the **optimize_fn**, but it wasn't changed at all.

```
head_embedding2 = head_embedding
for n in range(n_epochs):  # running optimization
    ~
(head_embedding == head_embedding2).all()  # check if changed
return head_embedding
```

Also tested with a short snippet code below to verify whether the process is inlined as you said, but it didn't.

```
import numba

def _fun(x):
    x = x+1

jitfun = numba.njit(_fun, fastmath=True, parallel=False)

x = 1
for n in range(10):
    jitfun(x)
print(x)
```

**Comment by lmcinnes** [comment]
I believe this comes down to pass by reference vs pass by value handling. Numpy arrays are all passed by reference. In contrast integers are passed by value. Thus your ``_fun`` sees a value, not a reference. If you were to instead do something like:

```python
import numba
import numpy as np

def _fun(x):
    x[0] = x[0] + 1

def test(x):
    _fun_jit = numba.njit(_fun)
    for n in range(10):
        _fun_jit(x)   
    return x

x = np.array([1])
for n in range(10):
    test(x)

print(x)
```

So that instead of passing an integer/value you are passing a container (in this case a numpy array) then the contents of the container, which is merely passed by reference, will get updated. The same would work if you passed a list instead of a numpy array, with the same causes. Indeed this will all go through without the numba compilation.

So why did you other code not find the change? Because assignment of numpy arrays is *also* by reference -- when you wrote

```python
head_embedding2 = head_embedding
```

you are not copying the contents of ``head_embedding`` into ``head_embedding2`` but merely the reference to the array, so ``head_embedding`` and ``head_embedding2`` point to the same location in memory, and it is that memory that is getting changed, thus because they point to the same place, the result is no difference between them. If you want to see the difference you need to explicitly make a copy of the *content* of the array. You can do that with the ``copy`` method. This will make ``head_embedding2`` a frozen copy of what ``head_embedding`` was at the start of the loop; then when you do the comparison you will see the difference. So you want:

```python
head_embedding2 = head_embedding.copy()
for n in range(n_epochs):  # running optimization
    ...
(head_embedding == head_embedding2).all()  # check if changed
return head_embedding
```

and you will see if there are changes, and there will be.

**Comment by damdaepark** [comment]
Oh, now I see. You avoided unnecessary instantiations. Thanks for the detailed explanation!
