### ISSUE TITLE
GPU Support for Parametric UMAP?

### ISSUE THREAD

**Issue by himaniyadav** [lmcinnes/umap#599]
Hello,

I read that UMAP doesn't currently have GPU support outside of the implementation in the NVIDIA RAPIDS cuML library, but I was wondering about Parametric UMAP, since this involves training a neural network. Currently my code is taking several hours to run with a custom encoder (a conv net that was specified in the example notebooks, using MNIST data). I also think I read in the Parametric UMAP paper that a GPU was used (but I'm not sure about that).

If GPU support is not available, are there any tips for speeding up the training of Parametric UMAP?

Thanks!

**Comment by timsainb** [comment]
Hi @himaniyadav. The Parametric UMAP implementation uses Tensorflow 2 as a backend. So long as you have GPU support in your tensorflow install, you have GPU support in Parametric UMAP. 

Maybe we should add a warning during training that lets you know whether a GPU is being used though.

**Comment by himaniyadav** [comment]
Okay, got it. After investigation I found that tensorflow is not picking up my GPU (though pytorch is, and it's definitely available for use) - so I'll have to look into that on my own. Thanks!

**Comment by lmcinnes** [comment]
Yes, if you are using ParametricUMAP then GPU support works for the optimization stage -- training the neural network. The rest of the operation (the graph / simplicial set construction) is still CPU code. Since ParametricUMAP is just using Tensorflow for the training simply managing to get your tensorflow installation using a GPU should be sufficient.
