### ISSUE TITLE
Reconstruction loss for Parametric UMAP

### ISSUE THREAD

**Issue by ayl** [lmcinnes/umap#618]
Thanks for the wonderful addition of Parametric UMAP to this repo. 

I was trying to get this to work on my own dataset which has grayscale images using an autoencoder setup and noticed that the reconstruction loss was not changing. I was looking through the repo and the code to see if I could understand why and I noticed that the reconstruction loss is currently BCE. 

https://github.com/lmcinnes/umap/blob/b1223505ca56ae104feb35e4196227277d1e8058/umap/parametric_umap.py#L299

Is there an option to make this MSE? Perhaps I am not understanding how the decoder works. 

@timsainb

**Comment by timsainb** [comment]
Hi ayl,

I agree, it would be reasonable to an option for MSE instead of BinaryCrossentropy for reconstruction. There should also be a weight to balance UMAP vs reconstruction loss (right now it's hardcoded at 1.0 `loss_weights["reconstruction"] = 1.0` https://github.com/lmcinnes/umap/blob/246c4d010ee3526fa5a43926947c6ae0f64929ab/umap/parametric_umap.py#L302). 
 Do you want to make a PR?
