### ISSUE TITLE
umap takes 10 seconds to import

### ISSUE THREAD

**Issue by jdkern11** [lmcinnes/umap#631]
First off, great work with umap, it's a very cool tool. 

I am trying to make a GUI that performs some mapping for a user. My issue is, it takes 10 seconds to import umap, which means the GUI start up is very slow. No other dependencies take this long, so I was wondering if there is some way to speed it up?

I have other features in the GUI, so ideally the user could perform other actions while the umap is created with cross threading. It's just the slow import that concerns me.

**Comment by lmcinnes** [comment]
I'm not actually sure what takes up time in the import phase. At least some of it may be related to numba compilation, but it could be any number of things. I can't offer any immediate solutions I am afraid.

**Comment by jdkern11** [comment]
That's okay, I found I could import/run it in a PySide2 worker thread in the background and the user can still operate the GUI while it's loading. I appreciate the quick response however!

**Comment by zapr-in** [comment]
It seems most of the time is taken by pynndescent
```shell_session
$ time python -c "import umap"
real	0m13.641s
user	0m13.729s
sys	0m0.518s

$ time python -c "import pynndescent"
real	0m13.315s
user	0m13.435s
sys	0m0.469s

```

**Comment by rsuhada** [comment]
Sorry to comment on this closed issue, but is there a way to speed up the import?
The PySide2 workaround is not applicable to my case.

UMAP gives very good results for my application and embedding calculation fast enough. However, we can't put it into production because the import is exceedingly long (cloud deployment).

Thank you!

**Comment by jdkern11** [comment]
Is the user uploading data that will be incorporated into the map? If not, you could premake the map and save the embedding, then just load the embedding to display.

**Comment by rsuhada** [comment]
The embedding has to be calculated for each user/session separately, so we can't use a cached one (and due to the system architecture, the library has to be imported at request time). 
The users are non-technical and can't wait 10 seconds for the results...

At the moment I've reverted to Kernel PCA (which is as expected not as good, but usable).

**Comment by jdkern11** [comment]
Can you add a loading bar to the interface? 10 seconds is slow but not so slow that most people would just leave if you have a loading bar.
