### ISSUE TITLE
Unable to use KL-Divergence as a metric

### ISSUE THREAD

**Issue by Thalaivar** [lmcinnes/umap#666]
My input data consists of 550 dimensional Morlet wavelet transform amplitudes, and I am trying to embed this in a 2-D space. However after running UMAP  I get the following warning (following which I get `ValueError` as UMAP runs into NaNs somewhere):
```
D:\Applications\anaconda3\envs\ddp\lib\site-packages\pynndescent\pynndescent_.py:924: UserWarning: Failed to correctly find n_neighbors for some samples.Results may be less than ideal. Try re-running withdifferent parameters.
  "Failed to correctly find n_neighbors for some samples.
```

The parameters I used for this run were `n_neighbors=60, min_dist=0.0, metric="symmetric_kl"`, however it fails even with the default values of `n_neighbors/min_dist`. 

I understand my question is probably vague but any suggestions on what I can do to avoid this error?

**Comment by lmcinnes** [comment]
It is just a warning, not an error; things will have run, but you may not have as good an embedding as you would wish. The issue is occurring because the approximate nearest neighbor search phase is failing to find enough neighbors for all the points. This can be caused by the data not fitting with the metric (symmetric_kl uses probability distributions, so each row of your data should sum to 1.0), samples that are particularly strange / outliers (an all zero vector, for example, will struggle to find any neighbors; similarly a vector that is completely orthogonal to the rest of the data will struggle to find neighbors), or simply data that is a little odd (if there is a small but very distinct cluster of, say, 50 samples that is far from anything else it may struggle to find 60 neighbors for each of those samples for example). It is hard to say for sure what the issue may be with your particular dataset, but hopefully these examples give you some ideas of things to look for.

**Comment by Thalaivar** [comment]
Thank you very much for your insights.

> (symmetric_kl uses probability distributions, so each row of your data should sum to 1.0)

Aren't the following lines taking care of that already?
https://github.com/lmcinnes/umap/blob/47b585cd27f4aa45737f91b4f0eb4aeea6bcc3d6/umap/distances.py#L774-L782

Also, it seemed that the issue was with my data. After changing up my feature extraction, the embedding executes smoothly, but is not what i'd expected, it looks like messy ramen spread out over a plane 😝

**Comment by lmcinnes** [comment]
Yes, it looks like those lines take care of it -- I had forgotten that there was appropriate normalization built in. I'm glad you got it working, but sorry to hear it was apparently not as informative as you would have liked.
