### ISSUE TITLE
run UMAP on Window? Linux? Jupyter? or R ?

### ISSUE THREAD

**Issue by jielab** [lmcinnes/umap#737]
Dear James:

I feel a bit dummy that i could not even get started by following the official UMAP tutorial https://umap-learn.readthedocs.io/en/latest/.

I am using Windows 10, with Ubuntu Linux enabled. I think this is quite standard for most of us. 
So, I am not using anything weird.

Previously, you recommended me to use Jupyter Notebook. I have no idea what that is, since I never used it before.
Now after a little bit reading, Is Jupyter Notebook basically a web interface, like below?
![image](https://user-images.githubusercontent.com/26947455/126897945-437bb30a-0718-4a56-87ed-2ac509199637.png)

Why should I write my UMAP commands at a web interface? We have Windows Powershell, we have Linux Shell, We also have R, why do I must type the UMAP commamds into a web interface? I could not get my heads around this ... 

Can someone please give me a step-by-step instruction here? I only want to follow this tutorial https://umap-learn.readthedocs.io/en/latest/. But right now, I could NOT show the following picture ...

![33](https://user-images.githubusercontent.com/26947455/126898104-424b5735-ea10-4c97-a150-0d81d59f6a51.PNG)

Best regadrs,
Jie

**Comment by jlmelville** [comment]
You have successfully installed the notebook software so that's a good start. The error message means that you now need to install UMAP into the same python environment that you installed the notebook software into so they can see each other. For example, if you used `conda` to install the notebook package you need to use `conda` to install the `umap-learn` package. Additionally, you need the `seaborn` package installed for visualization.

I have used WSL on Windows 10 with Ubuntu and have installed these on many occasions so I know it can be done, but it's hard to give exact instructions because there are so many ways to install things via Python all with their own advantages and disadvantages. The disadvantages can be quite substantial under some circumstances.

To clear up your other questions: you don't have to run UMAP in a notebook. But the reason so much tutorial material uses it is because, as you have discovered, the standard `python` interpreter does not display graphics the way e.g. R does. For projects where visualization is important, notebooks are the way to go.

**Comment by jielab** [comment]
Dear James:

Thank you very much. 

"Notebook" is a very confusing thing. As you mean, usually "notebook" just means a bunch of paper stacked together, or just a "laptop computer". So, "notebook" here you mean the "Jupyter Notebook", which is actually a web interface as I shown in the screenshot above, correct? 

I got the point that I need to use conda install umap-learn, and I did so. My question is: should I install it in Windows 10 instead of the Ubuntu LInux subsystem? Take R for example, I could generate a plot directly from Windows 10 R (typed into R console), but not from a Linux subsystem R command (typed into the Linux Shell). 

With all this difficulty stemming from the fact that  "t**he standard python interpreter does not display graphics the way e.g. R does**", can I simply run UMAP on Windows 10 version of R? I noticed that there is a UMAP package for R.

Best regards,
Jie

**Comment by jielab** [comment]
Don't know if it is JUST me, stupid, or something ...

I got a new laptop, Windows 10, I also activated the Ubuntu Linux (18.0.4) substyem for this laptop.

Now, I simply want to follow the steps at https://umap-learn.readthedocs.io/en/latest/basic_usage.html. however, I found that there is NO image showing up, after I typed the following command:

![aa](https://user-images.githubusercontent.com/26947455/126940101-4144c634-e64b-4ae3-a8a4-88d9d1cea28b.PNG)

I am not doing anything complicated... 

Can someone please kindly let me know how to solve this?

Best regadrs,
Jie

**Comment by jlmelville** [comment]
> So, "notebook" here you mean the "Jupyter Notebook", which is actually a web interface as I shown in the screenshot above, correct?

Yes. "notebooks" are also the name of the documents produced by the software and are ubiquitous in data-related Python projects.

> I got the point that I need to use conda install umap-learn, and I did so. My question is: should I install it in Windows 10 instead of the Ubuntu LInux subsystem? 

Whatever platform you are more confident in using python and installing packages with. It's actually easier to work with Linux.

> Take R for example, I could generate a plot directly from Windows 10 R (typed into R console), but not from a Linux subsystem R command (typed into the Linux Shell).

That is expected behavior with R. It's not the same with Python. I think your experience with R is giving you the wrong expectations with how code entered into the `python` shell works. You definitely *won't* see the plot unless you are running it in Jupyter Lab in your web browser. 

It works the same in Linux and Windows: if you enter the code into the prompt from typing `python` at the command line you *won't see any plots*. If you do it from Jupyter Lab in the web browser you *will* see the plot.

> With all this difficulty stemming from the fact that "t**he standard python interpreter does not display graphics the way e.g. R does**", can I simply run UMAP on Windows 10 version of R? I noticed that there is a UMAP package for R.

Yes you can do that too. But as you have successfully installed `jupyterlab` *and* separately installed `umap-learn`, I am sure with a little perseverance you will be able to get them working together. 

The following will install everything and run Jupyter Lab such that you can at least generate the penguin data pair plot from the tutorial (because this is what I use with WSL running Ubuntu):

```bash
sudo apt-get install --yes python3-venv
mkdir umap
cd umap
python3 -m venv venv
source venv/bin/activate
pip install -U pip setuptools wheel
pip install umap-learn seaborn jupyterlab
jupyter-lab
```

this uses `pip` rather than `conda` to install packages, so if you don't know what all of those commands do (e.g. if you aren't comfortable using `pip` and virtual environments), then you should reach out to someone who can help you with your specific Linux administration or python package installation needs.

**Comment by jielab** [comment]
Dear James:

I finally got this figured out. I only need to put "--no-browser" after "jupyter lab". Otherwise, "jupyter lab" called from my Linux substyem will do something weird and it can NOT open the Jupyter web interface. Instead, I need to manually paste the URL into a web browser after I typed "jupyter lab --no-browser".

I still hope there is a way to type the commands in the UMAP tutorial (https://umap-learn.readthedocs.io/en/latest/basic_usage.html)  in the Linux shell directly and collect all output images in a directory, so that i could streamline this part of work in a pipeline.

But for now, I am all set.

THANK YOU SO MUCH AGAIN!

Best Regards,
jie
