### ISSUE TITLE
installing umap 

### ISSUE THREAD

**Issue by hmassalha** [lmcinnes/umap#74]
I am using windows os (Python 3.6.5) and I am facing problems to make umap running on my machine. 
Running the `pip install umap-learn` line on a bash terminal, I get: 
`$ pip install umap-learn
Requirement already satisfied: umap-learn in c:\users\hassan\appdata\local\programs\python\python36-32\lib\site-packages (0.2.3)
Requirement already satisfied: scikit-learn>=0.16 in c:\users\hassan\appdata\local\programs\python\python36-32\lib\site-packages (from umap-l
earn) (0.19.1)
Requirement already satisfied: scipy>=0.19 in c:\users\hassan\appdata\local\programs\python\python36-32\lib\site-packages (from umap-learn) (
1.1.0)
Requirement already satisfied: numba>=0.34 in c:\users\hassan\appdata\local\programs\python\python36-32\lib\site-packages (from umap-learn) (
0.38.0)
Requirement already satisfied: numpy>=1.8.2 in c:\users\hassan\appdata\local\programs\python\python36-32\lib\site-packages (from scipy>=0.19-
>umap-learn) (1.14.3)
Requirement already satisfied: llvmlite>=0.23.0dev0 in c:\users\hassan\appdata\local\programs\python\python36-32\lib\site-packages (from numb
a>=0.34->umap-learn) (0.23.0)`

and if I run the `import umap` from Python, I get the following: 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Hassan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\umap\__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "C:\Users\Hassan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\umap\umap_.py", line 20, in <module>
    import umap.sparse as sparse
  File "C:\Users\Hassan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\umap\sparse.py", line 9, in <module>
    from umap.utils import (tau_rand_int,
  File "C:\Users\Hassan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\umap\utils.py", line 268, in <module>
    @numba.njit(parallel=True)
  File "C:\Users\Hassan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\numba\decorators.py", line 236, in njit
    return jit(*args, **kws)
  File "C:\Users\Hassan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\numba\decorators.py", line 141, in jit
    raise RuntimeError(msg)
RuntimeError: The 'parallel' target is not currently supported on Windows operating systems when using Python 2.7, or on 32 bit hardware.`

Any idea how to make umap working on my machine? I need it for Seurat package in R... but first it should be installed without errors. 

Thanks a lot, 
HM

**Comment by lmcinnes** [comment]
Unfortunately windows 32-bit machines are a bit of a weak-spot for UMAP because it relies on Numba for a lot of the performance heavy lifting and it has some issues on windows32. I believe you can get in working, but it won't be "clean". I believe the main feature that is an obstruction here is the use of the parallel option (which doesn't work for win32). You can remove that and then it *should* work.

How does one go about removing that? UMAP is all in python so you can just go in an edit the installed code.  You'll want to go through all the files in 
``C:\Users\Hassan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\umap\``
and wherever you see a line that says
``@numba.njit(parallel=True)``
or similar just remove the ``parallel=True``. I know that is not exactly an ideal solution, but it will at least get it working for you.

**Comment by hmassalha** [comment]
Thanks for your input, I will follow your instructions hopefully I will be able to use the package. HM

**Comment by sleighsoft** [comment]
Seems to be resolved.
