### ISSUE TITLE
UMAP API Guide missing 

### ISSUE THREAD

**Issue by rhysnewell** [lmcinnes/umap#753]
Hey Leland, 

Just noticed the API guide on the read the docs website has gone missing:  https://umap-learn.readthedocs.io/en/latest/api.html
Maybe a stray a commit accidentally deleted it? The rest of documentation seems okay, it's just the API guide that's been affected. Not a huge issue, and hopefully easy to fix

Cheers,
Rhys

**Comment by sgbaird** [comment]
Also seeing this. Going with GitHub searches in the meantime.

**Comment by lmcinnes** [comment]
In theory it is autogenerated by sphinx, but apparently something has gone astray with configurations there somewhere. I'll look into it, but I must admit that sphinx + readthedocs configuration subtleties are not my strong point.

**Comment by lmcinnes** [comment]
Huh. That turned out to be easy, but I see why it wasn't obvious that something bad might happen.

A recent PR added tqdm progress bars to show progress when UMAP is training (assuming verbose mode is on). The doc_requirements.txt is a separate requirements file that readthedocs runs, and it didn't have tqdm. The docs all built fine, just with an error in the log about the import failure, which cascaded to the autodoc failing to run properly. Fixed now, and the API docs should be back up soon (once readthedocs finishes building from the latest commits).

**Comment by sgbaird** [comment]
What you said makes sense, including why that wouldn't be obvious. Nice figuring it out!

**Comment by rhysnewell** [comment]
I'll close this now, thanks for fixing!
