### ISSUE TITLE
Reproducibility with large matrices

### ISSUE THREAD

**Issue by engelsdaniel** [lmcinnes/umap#760]
Hi,

if I run UMAP on arrays with more than 10,000 rows I cannot reproduce the embeddings after restarring the kernel even though I control for random_state. With slices of the same array (1,000 rows) it works perfectly.
Thanks in advance for any help! 

Best,
Daniel

**Comment by lgpreston75** [comment]
Are you using `n_jobs`? If so, check out the docs:

_"Since version 0.4 UMAP also support multi-threading for faster performance; when performing optimization this exploits the fact that race conditions between the threads are acceptable within certain optimization phases. Unfortunately this means that the randomness in UMAP outputs for the multi-threaded case depends not only on the random seed input, but also on race conditions between threads during optimization, over which no control can be had. This means that multi-threaded UMAP results cannot be explicitly reproduced."_

https://umap-learn.readthedocs.io/en/latest/reproducibility.html

**Comment by engelsdaniel** [comment]
Good idea, Ihave tested this already, didn't improve the outcome. However, I found the reason. It's because the column order of the input array (which hold the features) was shuffled. I assume that large arrays are split before processing and thus the outcome is slightly different because the fragmented arrays are not the same is the column order is shuffled each time. Keeping a fixed order of the array solved the problem. Interesting.
