### ISSUE TITLE
How to use precomputed_knn in a GridsearchCV pipeline

### ISSUE THREAD

**Issue by notuntoward** [lmcinnes/umap#989]
I can run several of the examples in [Precomputed k-nn](https://umap-learn.readthedocs.io/en/latest/precomputed_k-nn.html#precomputed-k-nn) of the user docs, but none of the examples show how to use `precomputed_knn` within a `GridSearchCV `pipeline.  Has anyone gotten this to work?

When I run this:

```import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from umap import UMAP
from umap.umap_ import nearest_neighbors  
from sklearn.utils import check_random_state
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X, y = make_classification(n_samples=1000, n_features=10, n_informative=5,
                           n_redundant=2, n_classes=3, n_clusters_per_class=2)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

params_grid_pipeline = {
    "umap__n_neighbors": [5, 10, 20],
    "umap__n_components": [15, 25, 50],
    "svc__C": [10 ** k for k in range(-3, 5)],
}

random_seed_shared = 10 # KNN and UMAP must use same random stae to get the same answer
random_state_shared = check_random_state(random_seed_shared)

n_neighbors_max = max(params_grid_pipeline["umap__n_neighbors"])

knn_pre = nearest_neighbors(X,
                        n_neighbors=n_neighbors_max, # UMAP() reorgs to get smaller KNNS
                        metric='euclidean',
                        metric_kwds=None,
                        angular=False,
                        n_jobs=-1, # not necessary, is default already
                        random_state=random_state_shared)


umap = UMAP(precomputed_knn=knn_pre, random_state=random_state_shared)
pipeline_knn_pre = Pipeline([("umap", umap), ("svc", svc)])

clf_pipeline_knn_pre = GridSearchCV(pipeline_knn_pre, **params_grid_pipeline)
clf_pipeline_knn_pre.fit(X_train, y_train)
print("Accuracy on the test set with preKNN UMAP transformation: {:.3f}".format(
      clf_pipeline_knn_pre.score(X_test, y_test)))
```

I get the error message:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[34], line 25
     22 umap = UMAP(precomputed_knn=knn_pre, random_state=random_state_shared)
     23 pipeline_knn_pre = Pipeline([("umap", umap), ("svc", svc)])
---> 25 clf_pipeline_knn_pre = GridSearchCV(pipeline_knn_pre, **params_grid_pipeline)
     26 clf_pipeline_knn_pre.fit(X_train, y_train)
     27 print("Accuracy on the test set with preKNN UMAP transformation: {:.3f}".format(
     28       clf_pipeline_knn_pre.score(X_test, y_test)))

TypeError: __init__() got an unexpected keyword argument 'umap__n_neighbors'
```

**Comment by jlmelville** [comment]
First, your example needs a bit of tweaking because `svc` is undefined in the `Pipeline` (presumably it's a `LinearSVM()`?).

Second, the reported error isn't a UMAP problem, but the use of the `GridSearchCV` constructor, I recommend replacing `**params_grid_pipeline` with `param_grid=params_grid_pipeline`.

With that out of the way, I think pre-computing the knn has a lot of implementation issues that will be tough to solve. First, computing the knn should really be seen as part of the training, so only done on `X_train`, not `X` as a whole, or you have data leakage occuring where some level of knowledge of the test set is encoded in the knn. 

You have a more immediate problem if you *don't* do that anyway because when you pass the knn for the full dataset to UMAP, when you ask it to `fit` with `X_train`, it will notice that the knn has more entries than `X_train` and ignore the knn data. You will get a warning to that effect.

Unfortunately, using `nearest_neighbors` with `X_train` instead of `X` isn't going to solve your problems. The CV bit of `GridSearchCV` means that it will hold out some of the data for internal validation. This in turns that what is passed to UMAP for fitting has fewer items than `X_train` and again UMAP will spot that the knn is the wrong size, ignore it and warn you about it.

As it stands I don't think there is an easy way to workaround any of that.
